# Build dockerfile on change
name: Build Docker (Dockerfile)

on:
  push:
    paths:
    - 'Dockerfile'
    - '.github/workflows/build_docker.yml'
  pull_request:
    paths:
    - 'Dockerfile'
    - '.github/workflows/build_docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build Tools
    - name: Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: andersenlab/bam_toolbox
        username: ${{ secrets.KSE_DOCKER_USER }}
        password: ${{ secrets.KSE_DOCKER_PASS }}
        snapshot: true
        dockerfile: Dockerfile
        workdir: "."
        tags: latest,${{ steps.current-time.formattedTime }}
        cache: true